[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
CONSOLE=Console/dsp

[internal]
exten => 6001,1,NoOp(Call local test extension 6001)
 same => n,Dial(PJSIP/6001,20)
 same => n,Hangup()

[outbound]
exten => _X.,1,NoOp(Outbound call to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@outbound-trunk,30)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Inbound call from trunk to ${EXTEN})
 same => n,Hangup()
