[global]
type=global
user_agent=MiniSIPCallCenter

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=8.163.96.127
external_media_address=8.163.96.127
local_net=10.0.0.0/8
local_net=172.16.0.0/12
local_net=192.168.0.0/16

[6001]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw
auth=6001
aors=6001
direct_media=no

[6001]
type=auth
auth_type=userpass
username=6001
password=6001

[6001]
type=aor
max_contacts=1

[outbound-trunk]
type=endpoint
context=from-trunk
disallow=all
allow=ulaw,alaw
aors=outbound-trunk-aor
direct_media=no
from_user=02032730801
from_domain=218.245.102.33
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[outbound-trunk-aor]
type=aor
contact=sip:218.245.102.33:6876

[outbound-trunk-identify]
type=identify
endpoint=outbound-trunk
match=218.245.102.33
